// Code generated by sqlc. DO NOT EDIT.
// source: diary.sql

package db

import (
	"context"
	"database/sql"
)

const createDiary = `-- name: CreateDiary :execresult
INSERT INTO diary (
    content,
    user_email
) VALUES (
    $1, $2
)
`

func (q *Queries) CreateDiary(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDiary)
}

const getDiary = `-- name: GetDiary :one
SELECT id, content, user_email, created_at FROM diary
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDiary(ctx context.Context) (Diary, error) {
	row := q.db.QueryRowContext(ctx, getDiary)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserEmail,
		&i.CreatedAt,
	)
	return i, err
}
