// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Diary struct {
	ID        int32          `json:"id"`
	Content   sql.NullString `json:"content"`
	UserEmail string         `json:"user_email"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	Email     string    `json:"email"`
	Gender    string    `json:"gender"`
	Age       int32     `json:"age"`
	Country   int32     `json:"country"`
	CreatedAt time.Time `json:"created_at"`
}
